## Regularization
- Regularization is a way to scale features of different magnitude to similar magnitute so that a optimizer can converge easily and without extreme intercept while maintaining original relationship amongst each other.
- There are couple of regularization methods
    - **L1 Regularization:** Where each random variables are divided by the sum of the absolute values
    - **L2 Regularization:** Where each random variables are divided by the square root of the sum of the squares
    - **Min Max Regularization:** Where each random variables are shrunk to a scale of 0 and 1
    - **StandardScaler:** Scale around mean and standardize it. RV becomes standard normal variables

In [11]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
import matplotlib.pyplot as plt
from IPython.display import display_html
from IPython.display import Markdown
import warnings
warnings.filterwarnings('ignore')

## DATA

In [12]:
temp = pd.DataFrame([ [4,1,2,2], [1,3,5,3] , [2,2,5,3]])
temp.columns = ["A","B","C","D"]
temp

   A  B  C  D
0  4  1  2  2
1  1  3  5  3
2  2  2  5  3

## L1 Regularization
Where each random variables are divided by the sum of the absolute values

Each random variables can be negative or positive
$$\mathbb{Y} = \{ y_n \in \mathbb{R} \}$$

$$\omega = \sum_{n=0}^{N} {|y_n|} $$

After regularization the random variables will be positive
$$\mathbb{Y} / \omega = \{ y_n \in \mathbb{R} : y_n > 0 \}$$

In [16]:
print("*" * 83)
print(" Scikit learn does it WRONG where it applies it row wise which is definitely wrong")
print("*" * 83)
print("\n")
l1 = Normalizer(norm="l1")
print(l1.fit_transform(temp))
print("\n")

print("*" * 20)
print("   THE WRIGHT WAY")
print("*" * 20)
display_html(temp.div(temp.abs().sum()))
print("\n")

print("*" * 50)
print("         If you insist on scikit learn then")
print("*" * 50)
print("\n")
l1 = Normalizer(norm="l1")
print(l1.fit_transform(temp.T).T)

***********************************************************************************
 Scikit learn does it WRONG where it applies it row wise which is definitely wrong
***********************************************************************************


[[0.44444444 0.11111111 0.22222222 0.22222222]
 [0.08333333 0.25       0.41666667 0.25      ]
 [0.16666667 0.16666667 0.41666667 0.25      ]]


********************
   THE WRIGHT WAY
********************

,A,B,C,D
0,0.571429,0.166667,0.166667,0.250
1,0.142857,0.500000,0.416667,0.375
2,0.285714,0.333333,0.416667,0.375

**************************************************
         If you insist on scikit learn then
**************************************************


[[0.57142857 0.16666667 0.16666667 0.25      ]
 [0.14285714 0.5        0.41666667 0.375     ]
 [0.28571429 0.33333333 0.41666667 0.375     ]]

## L2 Regularization
Where each random variables are divided by the square root of the sum of the squares of each

Each random variables can be negative or positive
$$\mathbb{Y} = \{ y_n \in \mathbb{R} \}$$

$$\omega = \sqrt{\sum_{n=0}^{N} {y_n^2} }$$

After regularization the random variables will be positive
$$\mathbb{Y} / \omega = \{ y_n \in \mathbb{R} : y_n > 0 \}$$

In [18]:
print("*" * 83)
print(" Scikit learn does it WRONG where it applies it row wise which is definitely wrong")
print("*" * 83)
print("\n")
l2 = Normalizer(norm="l2")
print(l2.fit_transform(temp))
print("\n")

print("*" * 83)
print("   THE WRIGHT WAY. Also luckily pandas does column wise computation by default")
print("*" * 83)
display_html( temp/ np.sqrt((temp**2).sum()) )
print("\n")

print("*" * 50)
print("     If you insist on using scikit learn then")
print("*" * 50)
print("\n")

l2 = Normalizer(norm="l2")
print(l2.fit_transform(temp.T).T)

***********************************************************************************
 Scikit learn does it WRONG where it applies it row wise which is definitely wrong
***********************************************************************************


[[0.8        0.2        0.4        0.4       ]
 [0.15075567 0.45226702 0.75377836 0.45226702]
 [0.3086067  0.3086067  0.77151675 0.46291005]]


***********************************************************************************
   THE WRIGHT WAY. Also luckily pandas does column wise computation by default
***********************************************************************************

,A,B,C,D
0,0.872872,0.267261,0.272166,0.426401
1,0.218218,0.801784,0.680414,0.639602
2,0.436436,0.534522,0.680414,0.639602

**************************************************
     If you insist on using scikit learn then
**************************************************


[[0.87287156 0.26726124 0.27216553 0.42640143]
 [0.21821789 0.80178373 0.68041382 0.63960215]
 [0.43643578 0.53452248 0.68041382 0.63960215]]

## Min Max regularization
Each random variables can be negative or positive
$$\mathbb{Y} = \{ y_n \in \mathbb{R} \}$$

$$\mathbb{X} = \dfrac{y_n - min( \mathbb{Y} )} {max( \mathbb{Y} ) - min( \mathbb{Y} )}$$

After normalization
$$\mathbb{X} = \{ x_n \in \mathbb{R} : 0 \leq y_n \leq 1 \}$$

In [69]:
print("*" * 83)
print(" Scikit learn does it WRONG where it applies it row wise which is definitely wrong")
print("*" * 83)
print("\n")
l_max = Normalizer(norm="max")
print(l_max.fit_transform(temp))
print("\n")

print("*" * 83)
print("   THE WRIGHT WAY. Also luckily pandas does column wise computation by default")
print("*" * 83)
display_html( (temp - temp.min()) / (temp.max() - temp.min()) )
print("\n")

print("*" * 50)
print("     If you insist on using scikit learn then")
print("*" * 50)
print("\n")

l_max = Normalizer(norm="max")
print(l_max.fit_transform(temp.T).T)

***********************************************************************************
 Scikit learn does it WRONG where it applies it row wise which is definitely wrong
***********************************************************************************


[[1.   0.25 0.5  0.5 ]
 [0.2  0.6  1.   0.6 ]
 [0.4  0.4  1.   0.6 ]]


***********************************************************************************
   THE WRIGHT WAY. Also luckily pandas does column wise computation by default
***********************************************************************************

,A,B,C,D
0,1.000000,0.0,0.0,0.0
1,0.000000,1.0,1.0,1.0
2,0.333333,0.5,1.0,1.0

**************************************************
     If you insist on using scikit learn then
**************************************************


[[1.         0.33333333 0.4        0.66666667]
 [0.25       1.         1.         1.        ]
 [0.5        0.66666667 1.         1.        ]]

In [65]:
temp

   A  B  C  D
0  4  1  2  2
1  1  3  5  3
2  2  2  5  3

## Scaling around mean and standard deviation
Each random variables can be negative or positive
$$\mathbb{Y} = \{ y_n \in \mathbb{R} \}$$

After scaling
$$\color{blue}{Y \sim Normal \; (\mu=0,\sigma^2=1)}$$

In [61]:
print("*" * 100)
print("ddof = 0 to treat it as Population otherwise 1(default) to treat it as sample meaning divide by N-1")
print("*" * 100)
display_html((temp - temp.mean()) / temp.std(ddof=0))
print("\n")

print("*" * 90)
print("By default scikit-learn treats random variables as population")
print("*" * 90)
StandardScaler().fit_transform(temp)

****************************************************************************************************
ddof = 0 to treat it as Population otherwise 1(default) to treat it as sample meaning divide by N-1
****************************************************************************************************

,A,B,C,D
0,1.336306,-1.224745,-1.414214,-1.414214
1,-1.069045,1.224745,0.707107,0.707107
2,-0.267261,0.000000,0.707107,0.707107

******************************************************************************************
By default scikit-learn treats random variables as population
******************************************************************************************

array([[ 1.33630621, -1.22474487, -1.41421356, -1.41421356],
       [-1.06904497,  1.22474487,  0.70710678,  0.70710678],
       [-0.26726124,  0.        ,  0.70710678,  0.70710678]])